<?php
/**
 * @file
 * Code for the EC Handbook feature.
 */

include_once 'ec_handbook.features.inc';

function ec_handbook_form_node_form_alter(&$form, &$form_state, $form_id) {

  $content_type = $form['#node']->type;

  if ($content_type == 'handbook') {

    $handbookhome = '105';

    $form['book']['bid']['#title'] = 'Do now touch - auto picks Handbook Homepage';
    $form['book']['bid']['#default_value'] = $handbookhome;
  }
}
