<?php
/**
 * @file
 * ec_blog_post.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function ec_blog_post_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Commercial Services',
    'description' => '',
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '0342213a-50d4-4833-95f1-d0e80badaf11',
    'vocabulary_machine_name' => 'blog_categories',
    'metatags' => array(),
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Heating',
    'description' => '',
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '072eb183-bc11-4b7d-a55f-119946229324',
    'vocabulary_machine_name' => 'blog_categories',
    'metatags' => array(),
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Air Quality',
    'description' => '',
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '2214312d-cc24-49fd-bcda-d1b971dbf0c9',
    'vocabulary_machine_name' => 'blog_categories',
    'metatags' => array(),
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Insulation',
    'description' => '',
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '52fc4a96-45f1-471a-aca5-8b4950c938be',
    'vocabulary_machine_name' => 'blog_categories',
    'metatags' => array(),
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Energy Audits',
    'description' => '',
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '72e7510b-2d25-4336-ae60-b7e914e64712',
    'vocabulary_machine_name' => 'blog_categories',
    'metatags' => array(),
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Home Automation',
    'description' => '',
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '8d12f858-ed8e-4b61-8986-2309bef4a188',
    'vocabulary_machine_name' => 'blog_categories',
    'metatags' => array(),
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Air Conditioning',
    'description' => '',
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => 'a00a5eae-5df4-4bbe-88f2-d1e8f5ea32e5',
    'vocabulary_machine_name' => 'blog_categories',
    'metatags' => array(),
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Heating Choices',
    'description' => '',
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => 'ae234515-6040-4203-9c58-808bb5a7b2d9',
    'vocabulary_machine_name' => 'blog_categories',
    'metatags' => array(),
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Conferences and Events',
    'description' => '',
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => 'dd578866-ea33-4d03-aa41-1077b171fcce',
    'vocabulary_machine_name' => 'blog_categories',
    'metatags' => array(),
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Air Flow',
    'description' => '',
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => 'e2c608bd-f498-4bfc-a921-617184c96ce6',
    'vocabulary_machine_name' => 'blog_categories',
    'metatags' => array(),
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  return $terms;
}
